# Site settings
title: Zach Wade
tagline: "Personal site of Zach Wade"
url: "https://zachwa.de" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: fbusername
twitter: twusername
github: ghusername
googleplus: gusername
instagram: igusername

# Contact
email: "hello@zachwa.de" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
