# Site settings
title: Zach Wade
tagline: "Personal site of Zach Wade"
url: "https://zachwa.de" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/twitter_prof.jpg # be sure to change this image
twitter: zwad3
github: zwade

# Contact
email: "zach@dttw.tech" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
